### ISSUE TITLE
Get-MSCatalogUpdate throws 'The catalog.microsoft.com site has encountered an error. Please try again later.'

### ISSUE THREAD

**Issue by grmndev** [Marco-online/MSCatalogLTS#3] opened 2024-11-25 11:51 UTC
Since a few days **Get-MSCatalogUpdate** randomly throws 'The catalog.microsoft.com site has encountered an error. Please try again later.' error.
Initially it was rather rare but recently the error is being thrown in 80 - 90% of cases.
The Web version of MS Update Catalog works fine and does not throw any errors. However, it seems it takes more time now to return the results, so perhaps it's a timeout issue?

Below is a random example of searching for a KB time after time until valid results have been returned.
It was ran on Linux but it's the same on Windows.

UPDATE: as far as I was able to debug the script, the issue occurs after **Sort-CatalogRequest** calls **Invoke-CatalogRequest** with **POST** method in **$Params** set. Unfortunately, the script has never finished successfully when in debug mode, so I wasn't able to pinpoint any differences.

![2024-11-25_11-55](https://github.com/user-attachments/assets/2aa24afe-4ae9-4f70-abec-c99ab9d3df54)

**Comment by Marco-online** [comment] 2024-11-25 18:37
It can be related to timeouts or changes in the response times of the Microsoft Update Catalog site.
I can't reproduce the problem. 


Try to add TimeoutSec = 60 at Invoke-CatalogRequest 
_like example_

        $Params = @{
            Uri = $Uri
            Method = $Method
            Body = $ReqBody
            ContentType = "application/x-www-form-urlencoded"
            UseBasicParsing = $true
            ErrorAction = "Stop"
            TimeoutSec = 60
        }

**Comment by svetecs** [comment] 2024-11-26 03:25
I get the same error.  This also occurs on the original https://github.com/ryan-jan/MSCatalog that I was using prior to looking at this release.

**Comment by grmndev** [comment] 2024-11-27 13:08
Running a 1.0.5-beta command with -ShowDebug gives only this
`PS> Get-MSCatalogUpdate -Search kb5002619 -ShowDebug
DEBUG: Request https://www.catalog.update.microsoft.com/Search.aspx?q=kb5002619
DEBUG: Request completed in 1.0509855 seconds
WARNING: The catalog.microsoft.com site has encountered an error. Please try again later.
WARNING: We did not find any results for kb5002619
`

However, in $ErrorText variable, which is populated after **Invoke-CatalogRequest** is called in **Sort-CatalogResults** line 44, there is **8DDD0010** error id mentioned - perhaps that will help.
I only found a piece of advice to clean-up IE cookies etc. but it doesn't seem to help in my case as I am getting the same error on Windows as on Linux.

`PS> $ErrorText
Attributes           : {id, class}
ChildNodes           : {#text, span, #text}
Closed               : True
ClosingAttributes    : {}
EndNode              : HtmlAgilityPack.HtmlNode
FirstChild           : HtmlAgilityPack.HtmlTextNode
HasAttributes        : True
HasChildNodes        : True
HasClosingAttributes : False
Id                   : errorPageDisplayedError
InnerHtml            : 
                           [<span id="ctl00_catalogBody_errorHandler_textErrorNumberError" class="contentHeaderErrorNumber">Error number: </span>8DDD0010]
                       
InnerText            : 
                           [Error number: 8DDD0010]
                       
LastChild            : HtmlAgilityPack.HtmlTextNode
Line                 : 527
LinePosition         : 0
InnerStartIndex      : 25001
OuterStartIndex      : 24934
InnerLength          : 135
OuterLength          : 208
Name                 : div
NextSibling          : HtmlAgilityPack.HtmlTextNode
NodeType             : Element
OriginalName         : div
OuterHtml            : <div id="errorPageDisplayedError" class="contentHeaderErrorNumber">
                           [<span id="ctl00_catalogBody_errorHandler_textErrorNumberError" class="contentHeaderErrorNumber">Error number: </span>8DDD0010]
                       </div>
OwnerDocument        : HtmlAgilityPack.HtmlDocument
ParentNode           : HtmlAgilityPack.HtmlNode
PreviousSibling      : HtmlAgilityPack.HtmlTextNode
StreamPosition       : 24934
XPath                : /html[1]/body[1]/div[1]/form[2]/div[3]/table[1]/tr[1]/td[1]/div[1]/div[1]/div[2]
Depth                : 0
`

**Comment by Marco-online** [comment] 2024-11-27 15:21
Thanks for the detailed feedback!  its a difficult problem because i can't reproduce the problem on any of my systems.

I updated [Set-TempSecurityProtocol.ps1](https://github.com/Marco-online/MSCatalogLTS/blob/main/Private/Set-TempSecurityProtocol.ps1) and [Invoke-CatalogRequest.ps1](https://github.com/Marco-online/MSCatalogLTS/blob/main/Private/Invoke-CatalogRequest.ps1)

Let me know

**Comment by ITSNOTSTUPIDIFITWORKS** [comment] 2024-11-29 11:15
Hi,

I have the same issue with 1.0.4 and 1.0.5-beta (also the original MSCatalog).

DEBUG: Request https://www.catalog.update.microsoft.com/Search.aspx?q=Cumulative%20Update%20for%20Microsoft%20server%20operating%20system%20version%2021H2%20for%20x64-based%20Systems
DEBUG: Request completed in 2.5658202 seconds
WARNING: The catalog.microsoft.com site has encountered an error. Please try again later.
WARNING: We did not find any results for Cumulative Update for Microsoft server operating system version 21H2 for x64-based Systems

Searching for  "Cumulative Update for Microsoft server operating system version 21H2 for x64-based Systems"

I can see with fiddler that the module first makes a GET request to :

GET /Search.aspx?q=Cumulative%20Update%20for%20Microsoft%20server%20operating%20system%20version%2021H2%20for%20x64-based%20Systems HTTP/1.1


It looks like it gets a proper result, the links to the updates are there. I will attach the result to this comment.

The next thing I see in fiddler is a POST request to 
POST /Search.aspx?q=Cumulative%20Update%20for%20Microsoft%20server%20operating%20system%20version%2021H2%20for%20x64-based%20Systems HTTP/1.1

The result to the post request is an error:

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/Error.aspx?id=-1914896368">here</a>.</h2>
</body></html>

**Comment by Marco-online** [comment] 2024-11-29 19:01
@ITSNOTSTUPIDIFITWORKS Hi, cleaned code and removed some POST requests, try the files in the Zip file 
[1.0.5.1.zip](https://github.com/user-attachments/files/17962455/1.0.5.1.zip)

**Comment by Marco-online** [comment] 2024-12-01 16:46
Fixed with #CleanupCode

**Closed by Marco-online** 2024-12-01 16:46 UTC
